name: Actions Runner Controller Demo
on:
  workflow_dispatch:

env:
  KUBEVIRT_CONFIG_PASS: "Dennis test"
jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: uname -a
