---
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of nvme.
# Copyright (c) 2026 SUSE LLC
#
# Authors: Daniel Wagner <dwagner@suse.de>

name: Run nightly tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 01 * * *'

jobs:
  nightly-tests:
    if: ${{ github.event_name == 'workflow_dispatch' || github.repository == 'linux-nvme/nvme-cli' }}
    runs-on: arc-vm-dennis-nvme-cli
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "linux-blktests/blktests-ci"
      #We don't have to build the kernel here, as we have a cron job running on
      #the k8s cluster that builds the linus-master target nightly.
      - name: Run nvme-cli tests in VM
        uses: ./.github/actions/kubevirt-action
        with:
          kernel_version: linus-master
          vm_artifact_upload_dir: nvme-cli/tests/nvmetests/
          run_cmds: |
            #Preventing bash variable expension for the outer cat by using
            #single quotes around EOF
            cat > test.sh << 'EOF'
            #!/bin/bash
            set -e
            set -x
            uname -a
            git clone https://github.com/${{ github.repository }} /nvme-cli
            git config --global --add safe.directory /nvme-cli
            cd /nvme-cli
            git checkout ${{ github.sha }}
            CONTROLLER=$(echo "${BDEV0}" | sed 's/n[0-9]*$//')
            cat > tests/config.json << EOJ
            {
              "controller" : "${CONTROLLER}",
              "ns1": "${BDEV0}",
              "log_dir": "/nvme-cli/tests/nvmetests",
              "log_level": "DEBUG",
              "nvme_bin": "/nvme-cli/.build-ci/nvme"
            }
            EOJ
            cat tests/config.json

            scripts/build.sh -b release -c gcc tests
            EOF

            sudo chmod +x test.sh

            #Create shared volume mount point for artifact upload
            mkdir -p nvme-cli

            #Expose all devices to the container through the `privileged` flag.
            #
            #BDEV0 is an environment variable of the self-hosted runner instance
            #that contains a valid nvme namespace which is capable of the nvm
            #command set.

            sudo podman run --privileged \
            -v /dev:/dev \
            -e BDEV0 \
            -v "${PWD}/test.sh":"/test.sh" \
            -v "${PWD}/nvme-cli":"/nvme-cli":z \
            ghcr.io/linux-nvme/debian:latest /test.sh
            podman_exit=$?

            # Copy the results into the expected upload directory
            sudo cp -r nvme-cli/.build-ci/meson-logs \
              nvme-cli/tests/nvmetests 2>/dev/null || true

            exit $podman_exit
